Generate remote and local dockerfile with jinja2

diff --git a/gpi/backend/pi/Dockerfile.j2 b/gpi/backend/pi/Dockerfile.j2
--- a/gpi/backend/pi/Dockerfile.j2
+++ b/gpi/backend/pi/Dockerfile.j2
@@ -1,5 +1,7 @@
-FROM revolutionsystems/python:2.7-wee
-USER root
+FROM phusion/baseimage:0.9.22
+
+# Use baseimage-docker's init system.
+CMD ["/sbin/my_init"]
 
 ## Install dependencies
 WORKDIR /tmp
@@ -36,18 +38,54 @@ RUN echo "deb http://apt.postgresql.org/pub/repos/apt/ xenial-pgdg main" >> /etc
 	apt-get update -y &&\
   apt-get install -y postgresql-client-9.6
 
-## Clean up obsolete folders and packages
-RUN rm -rf /var/lib/apt/lists/*
-RUN rm -rf /tmp/*
+
+# If this is called "PIP_VERSION", pip explodes with "ValueError: invalid truth value '<VERSION>'"
+ENV PYTHON_PIP_VERSION 9.0.1
+RUN set -ex; \
+	\
+	wget -O get-pip.py 'https://bootstrap.pypa.io/get-pip.py'; \
+	\
+	python get-pip.py \
+		--disable-pip-version-check \
+		--no-cache-dir \
+		"pip==$PYTHON_PIP_VERSION" \
+	; \
+	pip --version; \
+	\
+	find /usr/local -depth \
+		\( \
+			\( -type d -a \( -name test -o -name tests \) \) \
+			-o \
+			\( -type f -a \( -name '*.pyc' -o -name '*.pyo' \) \) \
+		\) -exec rm -rf '{}' +;
+
+
+# Clean up APT when done.
+RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 
 WORKDIR /app
 
-# # Install pip requirements
+# Install pip requirements
 COPY ./requirements.txt .
 RUN	pip install --no-cache-dir -r requirements.txt
+
+# Install editable requirements
+COPY ./requirements_editable.txt .
+RUN	pip install --no-cache-dir -r requirements_editable.txt
 
 # Expose port 8000
 EXPOSE 8000
 
+{% if flavor == 'remote' -%}
+COPY ./piserver /app/piserver
+
+# # Install Bower components
+WORKDIR /app/piserver/piserver
+RUN bower --allow-root install
+{% endif %}
+
 # # Set default workdir
 WORKDIR /app/piserver
+
+
+# vim: set ft=Dockerfile
